lib/embers_web/router.ex
defmodule EmbersWeb.Router do
  use EmbersWeb, :router

  import EmbersWeb.UserAuth

  import Phoenix.LiveDashboard.Router

  alias EmbersWeb.Plugs.{CheckPermissions, GetPermissions}

  # See https://github.com/elixir-cldr/cldr/issues/135#issuecomment-629119938
  require EmbersWeb.Cldr

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)

    plug(:fetch_live_flash)
    # plug(:put_root_layout, {EmbersWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)

    plug(:fetch_current_user)

    plug(Cldr.Plug.SetLocale,
      apps: [:cldr, :gettext],
      from: [:accept_language, :path, :query],
      gettext: EmbersWeb.Gettext,
      cldr: EmbersWeb.Cldr
    )

    plug(:put_locale_to_session)

    plug(GetPermissions)
    plug(EmbersWeb.Plugs.LoadSettings)
    plug(EmbersWeb.Plugs.SelectLayout)
    plug(EmbersWeb.Plugs.ModData)
  end

  pipeline :live_layout do
    plug(:put_root_layout, {EmbersWeb.LayoutView, :root})
    plug(:require_authenticated_user)
  end

  pipeline :admin do
    plug(:accepts, ["html"])
    plug(CheckPermissions, permission: "access_backoffice")
  end

  defp put_locale_to_session(conn, _opts) do
    locale = Cldr.get_locale().language

    conn
    |> put_session(:locale, locale)
  end

  scope "/" do
    pipe_through([:browser, :admin])

    live_dashboard("/dashboard", ecto_repos: [Embers.Repo], metrics: EmbersWeb.Telemetry)
  end

  ## Authentication routes

  scope "/", EmbersWeb do
    pipe_through([:browser, :redirect_if_user_is_authenticated])

    get("/register", UserRegistrationController, :new)
    post("/register", UserRegistrationController, :create)
    get("/login", UserSessionController, :new)
    post("/login", UserSessionController, :create)
    get("/reset_password", UserResetPasswordController, :new)
    post("/reset_password", UserResetPasswordController, :create)
    get("/reset_password/:token", UserResetPasswordController, :edit)
    put("/reset_password/:token", UserResetPasswordController, :update)
  end

  scope "/", EmbersWeb do
    pipe_through([:browser, :require_authenticated_user])

    get("/users/settings", UserSettingsController, :edit)
    put("/users/settings", UserSettingsController, :update)
    get("/users/settings/confirm_email/:token", UserSettingsController, :confirm_email)
  end

  scope "/", EmbersWeb do
    pipe_through([:browser])

    delete("/logout", UserSessionController, :delete)
    get("/users/confirm", UserConfirmationController, :new)
    post("/users/confirm", UserConfirmationController, :create)
    get("/users/confirm/:token", UserConfirmationController, :confirm)
  end

  scope "/", EmbersWeb do
    pipe_through(:browser)

    get("/", PageController, :index)

    get("/static/rules", PageController, :rules)
    get("/static/faq", PageController, :faq)
    get("/static/acknowledgments", PageController, :acknowledgments)

    # Settings
    scope "/settings" do
      patch("/", SettingsController, :update)
      post("/reset_pass", SettingsController, :reset_pass)

      put("/account/update_password", SettingsController, :update_password)
      put("/account/update_email", SettingsController, :update_email)
      get("/account/confirm_email/:token", SettingsController, :confirm_email)

      patch("/profile/update_profile", SettingsController, :update_profile)
      post("/profile/update_cover", SettingsController, :update_cover)
      post("/profile/update_avatar", SettingsController, :update_avatar)

      # get("/security", SettingsController, :show_security)
    end

    scope "/settings" do
      pipe_through(:live_layout)

      get("/", SettingsController, :show_profile)
      get("/profile", SettingsController, :show_profile)
      get("/content", SettingsController, :show_content)
      get("/design", SettingsController, :show_design)
      live("/privacy", Settings.PrivacyLive.Index, :index)
      live("/security", Settings.SecurityLive.Index, :index)
    end

    # Feeds
    get("/timeline", TimelineController, :index)
    delete("/timeline/activity/:id", TimelineController, :hide_activity)
    get("/discover", DiscoverController, :index)

    # User profile
    get("/user/:user_id/timeline", UserController, :timeline)
    get("/@:username", UserController, :show)
    get("/@:username/followers", UserController, :show_followers)
    get("/@:username/following", UserController, :show_following)
    get("/@:username/card", UserController, :show_card)

    # Posts
    scope "/post" do
      post("/", PostController, :create)
      delete("/:id", PostController, :delete)
      get("/:hash", PostController, :show)
      get("/:hash/modal", PostController, :show_modal)

      # Post replies
      get("/:hash/replies", PostController, :show_replies)
      # Post Reactions
      post("/:hash/reactions", PostController, :add_reaction)
      delete("/:hash/reactions/:name", PostController, :remove_reaction)

      get("/:hash/reactions/overview", ReactionController, :reactions_overview)
      get("/:hash/reactions/:reaction_name", ReactionController, :reactions_by_name)
    end

    # Medias
    post("/medias", MediaController, :upload)

    # Links
    post("/links", LinkController, :process)

    # Favorites
    get("/favorites", FavoriteController, :list)
    post("/favorites/:post_id", FavoriteController, :create)
    delete("/favorites/:post_id", FavoriteController, :destroy)

    # Notifications
    get("/notifications", NotificationController, :index)
    put("/notifications/:id", NotificationController, :read)

    # Follows
    post("/user_follow", UserFollowController, :create)
    post("/user_follow/name", UserFollowController, :create_by_name)
    delete("/user_follow/:id", UserFollowController, :destroy)
    delete("/user_follow/name/:name", UserFollowController, :destroy_by_name)

    # Chat
    scope "/chat" do
      get("/", ChatController, :index)
      post("/", ChatController, :create)
      get("/conversations", ChatController, :list_conversations)
      get("/@:username", ChatController, :show)
      get("/:id/messages", ChatController, :show_messages)
      put("/:id", ChatController, :read)
    end

    # Tags
    get("/tag/:name", TagController, :show)
    put("/tag/:id", TagController, :update)

    get("/tags/popular", TagController, :list_popular)
    get("/tags/pinned", TagPinnedController, :list_pinned)

    # Tags subscriptions
    post("/tags/:tag_id/sub", TagSubscriptionController, :subscribe)
    delete("/tags/:tag_id/sub", TagSubscriptionController, :unsubscribe)

    # Search
    get("/search/:query", SearchController, :search)
    get("/search_typeahead/user/:username", SearchController, :user_typeahead)

    # Reports
    post("/reports/post/:post_id", ReportController, :create_post_report)

    # Subscriptions
    scope "/subs" do
      get("/", TagSubscriptionController, :index)
      get("/tags", TagSubscriptionController, :index)
    end

    # Blocks
    scope "/blocks" do
      get("/", BlockController, :index)
      post("/", BlockController, :create)
      delete("/:id", BlockController, :destroy)
    end

    scope "/moderation", Moderation do
      pipe_through(:admin)

      # Dashboard
      get("/", DashboardController, :index)

      # Audit
      get("/audit", AuditController, :index)

      # Bans
      get("/bans", BanController, :index)
      post("/bans/unban", BanController, :unban)
      post("/ban/user/:canonical", BanController, :ban)

      # Posts
      post("/post/update_tags", TagController, :update_tags)

      # Disabled posts
      get("/disabled_posts", DisabledPostController, :index)
      put("/disabled_posts/:post_id/restore", DisabledPostController, :restore)

      # Reports
      get("/reports", ReportsController, :index)
      put("/reports/post/:post_id", ReportsController, :resolve)

      put(
        "/reports/post/:post_id/nsfw_and_resolve",
        ReportsController,
        :mark_post_nsfw_and_resolve
      )

      put(
        "/reports/post/:post_id/disable_and_resolve",
        ReportsController,
        :disable_post_and_resolve
      )

      get("/reports/post/:post_id/comments", ReportsController, :show_comments)

      # Users
      get("/users", UserController, :index)
      get("/users/list.json", UserController, :list_users)
      put("/users/:user_id", UserController, :update)
      delete("/users/:user_id/avatar", UserController, :remove_avatar)
      delete("/users/:user_id/cover", UserController, :remove_cover)

      # Roles
      get("/roles", RoleController, :index)
      put("/roles/:role_id", RoleController, :update)
    end
  end
end

lib/embers/moderation/ban.ex
defmodule Embers.Moderation.Ban do
  @moduledoc false
  use Ecto.Schema

  import Ecto.Changeset

  @primary_key {:id, Embers.Hashid, autogenerate: true}
  schema "bans" do
    field(:reason, :string)
    field(:level, :integer, default: 0)
    field(:expires_at, :utc_datetime)
    field(:deleted_at, :utc_datetime)

    belongs_to(:user, Embers.Accounts.User, type: Embers.Hashid)

    timestamps()
  end

  def changeset(ban, attrs) do
    ban
    |> cast(attrs, [:user_id, :reason, :level, :expires_at])
  end
end

lib/embers_web/controllers/moderation/audit_controller.ex
defmodule EmbersWeb.Moderation.AuditController do
  @moduledoc false

  use EmbersWeb, :controller

  alias Embers.Audit

  def index(conn, params) do
    before = Map.get(params, "before")

    opts = [before: before]

    entries = Audit.list_entries(opts)

    conn
    |> assign(:entries, entries)
    |> render("index.html", page_title: gettext("Audit"))
  end
end

lib/embers_web/controllers/moderation/ban_controller.ex
defmodule EmbersWeb.Moderation.BanController do
  @moduledoc false

  use EmbersWeb, :controller

  alias Embers.Accounts
  alias Embers.Moderation

  alias EmbersWeb.Plugs.CheckPermissions

  action_fallback(EmbersWeb.FallbackController)

  plug(CheckPermissions, [permission: "ban_user"] when action in [:ban])

  def index(conn, params) do
    before = Map.get(params, "before")

    options = [before: before]

    bans = Moderation.list_all_bans(options)

    if params["entries"] == "true" do
      conn
      |> put_layout(false)
      |> Embers.Paginator.put_page_headers(bans)
      |> render("entries.html", bans: bans)
    else
      conn
      |> render("index.html", bans: bans, page_title: gettext("Bans"))
    end
  end

  def unban(conn, %{"user_id" => user_id}) do
    Moderation.unban_user(user_id)

    conn
    |> json(nil)
  end

  @doc """
  Action for banning users
  """
  def ban(conn, %{"canonical" => canonical} = params) do
    actor = conn.assigns.current_user

    duration = Map.get(params, "duration", 1)
    reason = Map.get(params, "reason")

    ban_opts = [
      duration: duration,
      reason: reason,
      actor: actor.id
    ]

    with %Accounts.User{} = user <- Accounts.get_by(%{"canonical" => canonical}),
         {:ok, _ban} <- Moderation.ban_user(user, ban_opts) do
      conn
      |> json(nil)
    else
      {:error, :already_banned} ->
        conn
        |> json(nil)
    end
  end
end

lib/embers_web/controllers/moderation/dashboard_controller.ex
defmodule EmbersWeb.Moderation.DashboardController do
  @moduledoc false

  use EmbersWeb, :controller

  def index(conn, _params) do
    last_users = Embers.Stats.Accounts.get_last_registered_users()

    conn
    |> assign(:last_users, last_users)
    |> render("index.html", page_title: gettext("Dashboard"))
  end
end

lib/embers_web/controllers/moderation/disabled_post_controller.ex
defmodule EmbersWeb.Moderation.DisabledPostController do
  @moduledoc false

  use EmbersWeb, :controller

  alias Embers.Posts

  def index(conn, params) do
    posts = Posts.list_disabled(before: params["before"])

    disabled_count = Posts.count_disabled()

    if params["entries"] == "true" do
      conn
      |> put_layout(false)
      |> Embers.Paginator.put_page_headers(posts)
      |> render("entries.html", posts: posts)
    else
      conn
      |> assign(:page_title, gettext("Disabled posts"))
      |> assign(:posts, posts)
      |> assign(:disabled_count, disabled_count)
      |> render("index.html")
    end
  end

  def restore(conn, %{"post_id" => post_id}) do
    user = conn.assigns.current_user

    with {:ok, post} <- Posts.get_post(post_id),
         {:ok, _} <- Posts.restore_post(post, actor: user) do
      conn
      |> json(nil)
    end
  end

  def prune(_conn, _params) do
    :not_implemented
  end
end

lib/embers_web/controllers/moderation/post_controller.ex
defmodule EmbersWeb.Moderation.PostController do
  @moduledoc false

  use EmbersWeb, :controller

  action_fallback(EmbersWeb.FallbackController)
end

lib/embers_web/controllers/moderation/reports_controller.ex
defmodule EmbersWeb.Moderation.ReportsController do
  @moduledoc false

  use EmbersWeb, :controller

  alias Embers.Posts
  alias Embers.Reports
  alias Embers.Reports.PostReport

  alias EmbersWeb.Plugs.CheckPermissions

  action_fallback(EmbersWeb.FallbackController)

  plug(CheckPermissions, permission: "access_reports_queue")

  def index(conn, params) do
    posts_reports = PostReport.list_reported_posts(pagination: [before: params["before"]])

    if params["entries"] == "true" do
      conn
      |> put_layout(false)
      |> Embers.Paginator.put_page_headers(posts_reports)
      |> render("entries.html", posts_reports: posts_reports)
    else
      conn
      |> render("index.html", posts_reports: posts_reports, page_title: gettext("Reports"))
    end
  end

  def resolve(conn, %{"post_id" => post_id}) do
    with {:ok, post} <- Posts.get_post(post_id),
         :ok <- Reports.resolve_for(post) do
      conn
      |> json(nil)
    end
  end

  def mark_post_nsfw_and_resolve(conn, %{"post_id" => post_id}) do
    with(
      {:ok, post} <- Posts.get_post(post_id),
      {:ok, _tag} <- Embers.Tags.add_tag(post, "nsfw")
    ) do
      Reports.resolve_for(post)

      conn
      |> json(nil)
    end
  end

  def disable_post_and_resolve(conn, %{"post_id" => post_id}) do
    user = conn.assigns.current_user

    with(
      {:ok, post} <- Posts.get_post(post_id),
      {:ok, post} = Posts.delete_post(post, actor: user.id)
    ) do
      Reports.resolve_for(post)

      EmbersWeb.Endpoint.broadcast!(
        "post:#{post.id}",
        "deleted",
        %{}
      )

      conn
      |> json(nil)
    end
  end

  def show_comments(conn, %{"post_id" => post_id} = params) do
    with {:ok, post} <- Posts.get_post(post_id) do
      comments = Reports.get_comments_per_user(post, limit: 10, before: params["before"])

      render(conn, "comments.json", comments: comments)
    end
  end
end

lib/embers_web/controllers/moderation/role_controller.ex
defmodule EmbersWeb.Moderation.RoleController do
  @moduledoc false

  use EmbersWeb, :controller

  alias Embers.Authorization.Roles

  action_fallback(EmbersWeb.FallbackController)

  def index(conn, _params) do
    roles = Roles.list_all()

    render(conn, "index.html", roles: roles)
  end

  def update(conn, %{"role_id" => role_id} = params) do
    with role when not is_nil(role) <- Roles.get_by_id(role_id),
         name = Map.get(params, "name", role.name),
         permissions = Map.get(params, "permissions", role.permissions),
         {:ok, role} <- Roles.update(role.name, %{name: name, permissions: permissions}) do
      render(conn, "role.json", role: role)
    else
      nil -> {:error, :not_found}
    end
  end
end

lib/embers_web/controllers/moderation/tag_controller.ex
defmodule EmbersWeb.Moderation.TagController do
  @moduledoc false

  use EmbersWeb, :controller

  alias Embers.Posts
  alias Embers.Tags
  alias EmbersWeb.Plugs.CheckPermissions

  action_fallback(EmbersWeb.FallbackController)

  plug(CheckPermissions, [permission: "update_post"] when action in [:update_tags])

  def update_tags(conn, %{"post_id" => post_id, "tag_names" => tag_names}) do
    tag_names = Enum.filter(tag_names, &Tags.Tag.valid_name?/1)

    with %Posts.Post{} = post <- get_post_with_tags(post_id) do
      Tags.update_tags(post, tag_names)
      post = get_post_with_tags(post_id)

      new_tags = Enum.map(post.tags, fn x -> x.name end)
      EmbersWeb.Endpoint.broadcast!("post:#{post_id}", "tags_updated", %{new_tags: new_tags})

      conn
      |> put_layout(false)
      |> put_view(EmbersWeb.PostView)
      |> render("post.html", post: post)
    else
      _ -> {:error, :not_found}
    end
  end

  defp get_post_with_tags(post_id) do
    post_id
    |> Posts.get_post!()
    |> Embers.Repo.preload(:tags)
  end
end

lib/embers_web/controllers/report_controller.ex
defmodule EmbersWeb.ReportController do
  @moduledoc false

  use EmbersWeb, :controller

  alias Embers.Posts
  alias Embers.Reports

  alias EmbersWeb.Plugs.CheckPermissions

  action_fallback(EmbersWeb.FallbackController)

  plug(CheckPermissions, [permission: "create_report"] when action in [:create])

  def create_post_report(conn, %{"post_id" => id} = params) do
    user = conn.assigns.current_user
    reportable = Posts.get_post!(id)

    attrs = [comments: params["comments"]]

    with {:ok, _report} <- Reports.report(reportable, user, attrs) do
      conn
      |> json(nil)
    else
      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_status(:unprocessable_entity)
        |> put_view(EmbersWeb.ErrorView)
        |> render("422.json", changeset: changeset)

      {:error, reason} ->
        conn
        |> put_status(:unprocessable_entity)
        |> put_view(EmbersWeb.ErrorView)
        |> render("422.json", %{error: reason})
    end
  end
end

lib/embers_web/views/moderation/ban_view.ex
defmodule EmbersWeb.Moderation.BanView do
  @moduledoc false

  use EmbersWeb, :view
end

lib/embers_web/views/moderation/dashboard_view.ex
defmodule EmbersWeb.Moderation.DashboardView do
  @moduledoc false

  use EmbersWeb, :view
end

lib/embers_web/templates/moderation/reports/_post_summary.html.eex
<div post-report-summary data-post-id="<%= @summary.post.id %>" data-author="<%= @summary.post.user.canonical %>">
  <article data-post-id="<%= @summary.post.id %>" class="post post-report-summary" data-controller="<%= attr_list [
      "medias",
      {"content-warning", @summary.post.nsfw }
    ] %>" <%= if @summary.post.nsfw, do: "nsfw" %>
    data-tags="<%= Enum.join(@summary.post.tags |> Enum.map(fn x -> x.name end), " ") %>">
    <div class="content-warnings">
      <div class="content-warning warning-nsfw">
        <span>NSFW: </span>
        <button class="button danger button-small" data-target="content-warning.button"
          data-action="content-warning#toggle">
          <%= gettext("Show") %>
        </button>
      </div>
    </div>
    <section class="post-wrapper">
      <%= if @summary.post.deleted_at do %>
      <div class="post-deleted-notice">Este post ha sido eliminado</div>
      <% end %>
      <header>
        <%= render(EmbersWeb.UserView, "avatar.html", avatar: @summary.post.user.meta.avatar.small, size: "medium") %>
        <div class="post-details">
          <div class="details-top">
            <%= labeled_link(@summary.post.user.username,
              to: decoded_path(:user_path, Endpoint, :show, @summary.post.user.canonical),
              label: @summary.post.user.username,
              class: "username"
            )
            %>
          </div>
          <div class="details-bottom">
            <%= link(to: Routes.post_path(Endpoint, :show, @summary.post.id), itemprop: "url") do %>
            <time datetime="<%= @summary.post.inserted_at %>" pubdate="<%= @summary.post.inserted_at %>"
              itemprop="datePublished">
              <%= time_ago(@summary.post.inserted_at) %>
            </time>
            <% end %>
            <%= link(to: Routes.post_path(Endpoint, :show, @summary.post.id), class: "post-id-link") do %>
            >><%= @summary.post.id %>
            <% end %>
          </div>
        </div>
      </header>
      <section class="post-content">
        <section class="post-body" itemprop="articleBody">
          <leg-markdown><%= @summary.post.body %></leg-markdown>
          <%= if !is_nil(@summary.post.related_to_id) do %>
          <%= link(to: Routes.post_path(Endpoint, :show, @summary.post.related_to_id), class: "related-link") do %>
          <%= " " <> Routes.post_url(Endpoint, :show, @summary.post.related_to_id) %>
          <% end %>
          <% end %>
        </section>
        <%= if length(@summary.post.media) > 0 do %>
        <section class="post-medias">
          <%= EmbersWeb.PostView.render("_media_group.html", medias: @summary.post.media) %>
        </section>
        <% end %>
        <%= if length(@summary.post.links) > 0 do %>
        <%= for link <- @summary.post.links do %>
        <%= EmbersWeb.LinkView.render("link.html", link: link) %>
        <% end %>
        <% end %>
      </section>
      <post-tags data-post_id="<%= @summary.post.id %>"></post-tags>
    </section>
    <media-gallery data-target="medias.gallery">
      <%= if (length @summary.post.links) > 0 do %>
      <%= for link <- @summary.post.links do %>
      <gallery-item data-id="<%= link.id %>" data-type="image" data-src="<%= link.embed.thumbnail_url %>">
      </gallery-item>
      <% end %>
      <% end %>
      <%= for media <- @summary.post.media do %>
      <gallery-item data-id="<%= media.id %>" data-type="<%= media.type %>"
        data-src="<%= Embers.Media.format_url media.url %>"></gallery-item>
      <% end %>
      </media-galley>
  </article>
  <div class="post-report-summary-actions">
    <p><%= ngettext("Reported 1 time", "Reported %{count} times", @summary.count) %></p>
    <p class="post-report-summary-reason">
      <%= @summary.main_reason %>
    </p>
    <button class="plain-button see-report-reasons" data-action="show_comments">Ver motivos de reporte</button>
    <div class="post-report-actions">
      <button class="button" data-action="resolve">Conservar</button>
      <button class="button" data-action="flag_nsfw">Marcar como NSFW</button>
      <button class="button" data-action="ban-user">Suspender usuario</button>
      <button class="button danger" data-action="disable">Eliminar</button>
    </div>
  </div>
  <report-reasons-dialog data-post-id="<%= @summary.post.id %>"></report-reasons-dialog>
</div>

lib/embers_web/templates/moderation/reports/entries.html.eex
<%= for summary <- @posts_reports do %>
  <%= render("_post_summary.html", summary: summary, conn: @conn) %>
<% end %>

lib/embers_web/templates/moderation/reports/index.html.eex
<%= EmbersWeb.LayoutView.sidebar(assigns) do %>
<%= render(EmbersWeb.Moderation.SharedView, "_sidebar.html", assigns) %>
<% end %>
<div id="view" view="moderation-reports" class="has-sidebar">
  <%= render_shared("top_bar.html", assigns) %>
  <main class="padded" infinite-scroll data-source="/moderation/reports" data-next="<%= @posts_reports.next %>"
    data-last-page="<%= @posts_reports.last_page %>">
    <h1><%= gettext("Reports") %></h1>

    <section infinite-scroll-viewport>
      <%= if Enum.empty?(@posts_reports) do %>
      <p class="reached-bottom-notice"><%= gettext("Hooray! There are no reports") %></p>
      <% end %>
      <%= for summary <- @posts_reports do %>
      <%= render("_post_summary.html", summary: summary, conn: @conn) %>
      <% end %>
    </section>
    <intersect-observer infinite-scroll-intersect></intersect-observer>
    <loading-indicator infinite-scroll-indicator></loading-indicator>
  </main>
</div>